Initial commit after forking repository

diff --git a/rootfs/usr/bin/nord_login b/rootfs/usr/bin/nord_login
--- a/rootfs/usr/bin/nord_login
+++ b/rootfs/usr/bin/nord_login
@@ -1,34 +1,34 @@
 #!/bin/bash
 
-if ! iptables -L > /dev/null 2>&1; then
-  echo "FATAL: iptables is not functional. Ensure your container config adds --cap-add=NET_ADMIN,NET_RAW" 1>&2
+if ! iptables -L > /dev/null 2>&1
+then
+  echo -e "$(date "+%F %T%z")\tWARNING\tiptables is not functional. Ensure your container capabilities include NET_ADMIN" 1>&2
   # Null route rather than leaving traffic unprotected.
   ip route del default
   ip route del 0.0.0.0/1 > /dev/null 2>&1
   ip route add default via 127.0.0.1
-  echo "--- Due to errors, routing has been disabled ---" 1>&2
-  # Don't allow execution to proceed as traffic may not be protected. Don't exit either as 
+  echo -e "$(date "+%F %T%z")\tWARNING\tDue to errors, routing has been disabled and further execution halted; please check your container configuration" 1>&2
+  # Don't allow execution to proceed as traffic may not be protected. Don't exit either as
   # containers that expect to be behind the VPN will route through the normal network.
-  while true; do
+  while true
+  do
     sleep 3600
   done
 fi
 
-while [ ! -S /run/nordvpn/nordvpnd.sock ] ; do
-  sleep 1
-done
-
-[[ -z "${TOKEN}" ]] && [[ -f "${TOKENFILE}" ]] && TOKEN="$(head -n 1 "${TOKENFILE}")"
-nordvpn logout --persist-token > /dev/null
-
-if [[ -n ${TOKEN} ]]; then
-  nordvpn login --token "${TOKEN}" || {
-    echo "Invalid token."
+## only token is viable in a container
+nordvpn logout --persist-token > /dev/null 2>&1
+[[ -z "${TOKEN}" ]] && [[ -f "${TOKEN_FILE}" ]] && TOKEN="$(head -n 1 "${TOKEN_FILE}")"
+if [[ -n ${TOKEN} ]]
+then
+  nordvpn login --token "${TOKEN}" > /dev/null || {
+    echo -e "$(date "+%F %T%z")\tWARNING\tInvalid token."
     exit 1
   }
 else
-  echo "No token set."
-  exit 1
+    echo -e "$(date "+%F %T%z")\tWARNING\tA token must be provided; only tokens are supported."
+    exit 1
 fi
-
+## Clear sensitive variables
+echo "Login successful; connection now in progress..."
 exit 0
